### ISSUE TITLE
MySQL SQL_TYPE does not exist

### ISSUE THREAD

**Issue by bsanders1979** [RDBI/rdbi-driver-odbc#2]
When querying a MySQL datasource, I get "undefined method `[]' for nil:NilClass" at rdbi-driver-odbc-0.1.2/lib/rdbi/driver/odbc.rb:215. The value of col.type is -9 (which I couldn't seem to verify anywhere) and the actual sql type is varchar. I simply copied/pasted the other varchar definition (12) and changed the key accordingly and resolved the issue. Thought you might like to know.

**Comment by semmons99** [comment]
Please submit a pull request with your change.

**Comment by bsanders1979** [comment]
That might take a minute. I'm not familiar w/ dvcs, so I need to figure out what exactly that means. I use SVN, so checking out code, making modifications, and submitting a patch is the process I know.
